const presetPlanData = {
  push_pull_leg: {
    monday: [
      {
        id: "1",
        exercise_name: "Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "2",
        exercise_name: "Incline Dumbbell Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "3",
        exercise_name: "Decline Dumbbell Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "4",
        exercise_name: "Shoulder Press",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "5",
        exercise_name: "Side lateral Raise",
        weight: "2.5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "6",
        exercise_name: "Reverse fly",
        weight: "2.5 kg",
        sets: 4,
        reps: 12,
      },
    ],
    wednesday: [
      {
        id: "1",
        exercise_name: "Lat Pulldown",
        weight: "22.5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "2",
        exercise_name: "Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "3",
        exercise_name: "Shrugs",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "4",
        exercise_name: "Reverse fly",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "5",
        exercise_name: "Hammer Curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "6",
        exercise_name: "Bicep curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
    ],
    friday: [
      {
        id: "1",
        exercise_name: "Squat",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Deadlift",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "3",
        exercise_name: "Leg Press",
        weight: "12.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "4",
        exercise_name: "Leg Curl",
        weight: "12.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "5",
        exercise_name: "Calf Raise",
        weight: "7.55 kg",
        sets: 4,
        reps: 20,
      },
    ],
  },
  fullbody: {
    monday: [
      {
        id: "1",
        exercise_name: "Squat",
        weight: "7.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Bench Press",
        weight: "7.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "3",
        exercise_name: "Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "4",
        exercise_name: "Bicep curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "5",
        exercise_name: "Leg Curl",
        weight: "8.5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "6",
        exercise_name: "Situp",
        weight: "Bodyweight",
        sets: 4,
        reps: 12,
      },
    ],
    wednesday: [
      {
        id: "1",
        exercise_name: "Deadlift",
        weight: "7.5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "2",
        exercise_name: "Shoulder Press",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "3",
        exercise_name: "Lat Pulldown",
        weight: "12.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "4",
        exercise_name: "Shrugs",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "5",
        exercise_name: "Calf Raise",
        weight: "7.5 kg",
        sets: 4,
        reps: 20,
      },
      {
        id: "6",
        exercise_name: "Plank",
        weight: "",
        sets: 4,
        reps: 60,
      },
    ],
    friday: [
      {
        id: "1",
        exercise_name: "Squat",
        weight: "7.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Incline Dumbbell Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "3",
        exercise_name: "Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "4",
        exercise_name: "Tricep Pushdown",
        weight: "8.5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "5",
        exercise_name: "Bicep curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "6",
        exercise_name: "Leg Curl",
        weight: "12.5 kg",
        sets: 4,
        reps: 6,
      },
    ],
  },
  upper_lower: {
    monday: [
      {
        id: "1",
        exercise_name: "Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "3",
        exercise_name: "Shoulder Press",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "4",
        exercise_name: "Lat Pulldown",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "5",
        exercise_name: "Side lateral Raise",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "6",
        exercise_name: "Bicep curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "7",
        exercise_name: "Tricep Pushdown",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
    ],
    tuesday: [
      {
        id: "1",
        exercise_name: "Squat",
        weight: "7.5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Deadlift",
        weight: "7.5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "3",
        exercise_name: "Calf Raise",
        weight: "7.5 kg",
        sets: 4,
        reps: 20,
      },
      {
        id: "4",
        exercise_name: "Leg Curl",
        weight: "7.5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "5",
        exercise_name: "Leg Press",
        weight: "12.5 kg",
        sets: 4,
        reps: 8,
      },
    ],
    thursday: [
      {
        id: "1",
        exercise_name: "Incline Dumbbell Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "3",
        exercise_name: "Shoulder Press",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "4",
        exercise_name: "Lat Pulldown",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "5",
        exercise_name: "Side lateral Raise",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "6",
        exercise_name: "Bicep curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "7",
        exercise_name: "Tricep Pushdown",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
    ],
    friday: [
      {
        id: "1",
        exercise_name: "Squat",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Deadlift",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "3",
        exercise_name: "Calf Raise",
        weight: "5 kg",
        sets: 4,
        reps: 20,
      },
      {
        id: "4",
        exercise_name: "Leg Curl",
        weight: "5 kg",
        sets: 4,
        reps: 6,
      },
      {
        id: "5",
        exercise_name: "Leg Press",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
    ],
  },
  antagonistic: {
    monday: [
      {
        id: "1",
        exercise_name: "Leg Curl",
        weight: "7.5 kg",
        sets: 4,
        reps: 15,
      },
      {
        id: "2",
        exercise_name: "Leg Press",
        weight: "12.5 kg",
        sets: 4,
        reps: 15,
      },
      {
        id: "3",
        exercise_name: "Lunge",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "4",
        exercise_name: "Reverse Lunge",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "5",
        exercise_name: "Calf Raise",
        weight: "7.5 kg",
        sets: 4,
        reps: 20,
      },
    ],
    tuesday: [
      {
        id: "1",
        exercise_name: "Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 8,
      },
      {
        id: "3",
        exercise_name: "Incline Dumbbell Bench Press",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "4",
        exercise_name: "Incline Dumbbell Row",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "5",
        exercise_name: "Dumbbell Chest fly",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "6",
        exercise_name: "Reverse fly",
        weight: "2.5 kg",
        sets: 4,
        reps: 12,
      },
    ],
    thursday: [
      {
        id: "1",
        exercise_name: "Pull-up",
        weight: "Bodyweight",
        sets: 4,
        reps: 8,
      },
      {
        id: "2",
        exercise_name: "Front raise",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "3",
        exercise_name: "Lat Pulldown",
        weight: "22.5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "4",
        exercise_name: "Side lateral Raise",
        weight: "5 kg",
        sets: 4,
        reps: 15,
      },
      {
        id: "5",
        exercise_name: "Shrugs",
        weight: "5 kg",
        sets: 4,
        reps: 15,
      },
    ],
    friday: [
      {
        id: "1",
        exercise_name: "Lying Triceps Extension",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "2",
        exercise_name: "Tricep Dumbbell Kickback",
        weight: "5 kg",
        sets: 4,
        reps: 10,
      },
      {
        id: "3",
        exercise_name: "Bicep curl",
        weight: "5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "4",
        exercise_name: "Tricep Pushdown",
        weight: "7.5 kg",
        sets: 4,
        reps: 12,
      },
      {
        id: "5",
        exercise_name: "Hammer Curl",
        weight: "5 kg",
        sets: 4,
        reps: 15,
      },
    ],
  },
};

module.exports = presetPlanData;
